"=============================================================================
" File:         dev/C++/blog/octopress/source/_posts/codes/test-opaques/_vimrc_local.vim {{{1
" Author:       Luc Hermitte <EMAIL:luc {dot} hermitte {at} gmail {dot} com>
"		<URL:http://github.com/LucHermitte/LucHermitte.github.io>
" Version:      0.0.1.
let s:k_version = 19
" Created:      12th Oct 2016
" Last Update:  12th Oct 2016
"------------------------------------------------------------------------
" Description:
"       «description»
"
"------------------------------------------------------------------------
" Installation:
"       The file must be present in a directory parent of every directories
"       where the definitions must apply.
" History:      «history»
" TODO:         «missing features»
" }}}1
"=============================================================================

" Always loaded {{{1

" Buffer-local Definitions {{{1
" Avoid local reinclusion {{{2
if &cp || (exists("b:loaded_dev_C_blog_octopress_source_posts_codes_test_opaques_vimrc_local")
      \ && (b:loaded_dev_C_blog_octopress_source_posts_codes_test_opaques_vimrc_local >= s:k_version)
      \ && !exists('g:force_reload_dev_C_blog_octopress_source_posts_codes_test_opaques_vimrc_local'))
  finish
endif
let b:loaded_dev_C_blog_octopress_source_posts_codes_test_opaques_vimrc_local = s:k_version
let s:cpo_save=&cpo
set cpo&vim
" Avoid local reinclusion }}}2

" ======================[ Check Path/Component {{{2
let s:script                = expand("<sfile>:p")
let s:script_dir            = expand('<sfile>:p:h')
let s:currently_edited_file = expand('%:p')
if empty(s:currently_edited_file) && (&ft != 'qf')
    let s:currently_edited_file = getcwd()
endif
" If this is a buffer generated by fugitive, abort!
if s:currently_edited_file =~ '^fugitive://'
  finish
endif

"------------------------------------------------------------------------
" Project settings {{{2
:Project --define opaque
let s:prj = lh#project#crt()
if lh#option#is_unset(lh#dict#get_composed(s:prj, 'variables.paths.sources'))
  :Project :cd %:h
endif

" LetTo p:$CXXFLAGS='-std=c++14'
" LetTo p:$CXX='g++-5'
LetTo p:$CXXFLAGS='-std=c++14 -fno-elide-type -stdlib=libc++'
LetTo p:$CXX='clang++'

QFImport b:crt_project

" ======================[ Other commands {{{2
command! -b -nargs=* LVEcho echo <sid>Echo(<args>)

"=============================================================================
" Global Definitions {{{1
" Avoid global reinclusion {{{2
if &cp || (exists("g:loaded_dev_C_blog_octopress_source_posts_codes_test_opaques_vimrc_local")
      \ && (g:loaded_dev_C_blog_octopress_source_posts_codes_test_opaques_vimrc_local >= s:k_version)
      \ && !exists('g:force_reload_dev_C_blog_octopress_source_posts_codes_test_opaques_vimrc_local'))
  let &cpo=s:cpo_save
  finish
endif
let g:loaded_dev_C_blog_octopress_source_posts_codes_test_opaques_vimrc_local = s:k_version
" Avoid global reinclusion }}}2
"------------------------------------------------------------------------

" ======================[ Misc function {{{2
" Function: s:Echo(expr) {{{3
function! s:Echo(expr)
  return a:expr
  " return eval(a:expr)
endfunction
"------------------------------------------------------------------------
" }}}1
"------------------------------------------------------------------------
let &cpo=s:cpo_save
"=============================================================================
" vim600: set fdm=marker:
